### ISSUE TITLE
Did ExcelReaderFactory.CreateOpenXmlReader create the file in Temp directory

### ISSUE THREAD

**Issue by splahostertest** [ExcelDataReader/ExcelDataReader#135]
We are using the ExcelReaderFactory.CreateOpenXmlReader to read the excel file. And reading the excel as DataSet. 
We are passing the file using memory stream.
Could please anyone confirm that while reading the file as Dataset, it will create the file in temp folder.
Code used as 

var reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
reader.IsFirstRowAsColumnNames = hasHeader;
var workbook = reader.AsDataSet(); 

stream object is memory stream object .

**Comment by wizardgsz** [comment]
Take a look at this new feature enhancement: it reads data directly from memory stream without writing temp files.

https://github.com/ExcelDataReader/ExcelDataReader/pull/114

**Comment by burakuytun** [comment]
Hello, 

I can't find the read from memory option on latest version? Did you remove that?

**Comment by wizardgsz** [comment]
It has not been released yet.
As stated before, please chose between the three proposed solutions (read above).
Thanks a lot!

**Comment by erw13n** [comment]
Just want to share, 
I face this problem couple of hours ago, Server run of disk space because ExcelReaderFactory.CreateOpenXmlReader create a so many Temp files this last couple of years.
So I'm using ExcelReaderFactory.CreateBinaryReader to load .xls file instead of .xlsx file, so far it didn't create any Temp file.
