### ISSUE TITLE
Remove ReadOption

### ISSUE THREAD

**Issue by appel1** [ExcelDataReader/ExcelDataReader#226]
Don't think it makes any sense. We try to support any Excel file that Excel itself can open. Unless we want to change the Strict option to really mean that we are strict and require the file to strictly follow the file format specification. Don't think anyone would use that.

Or are there files that we can open with ReadOption.Loose that Excel can't open?

**Comment by andersnm** [comment]
Here is the original commit:
https://exceldatareader.codeplex.com/SourceControl/changeset/82970

Apparently the test `Issue_11636_BiffStream` demonstrates why the flag was added, but the current develop branch has used strict in this test since 84355ebff382c9b1837a87c891b3e8089273382e.

Sounds like something else was fixed which eliminated the need for ReadOption. I agree to remove it
