### ISSUE TITLE
System.NotSupportedException about encoding when opening .xls file

### ISSUE THREAD

**Issue by corenting** [ExcelDataReader/ExcelDataReader#241]
Hello,

I'm using the 3.0.0-develop00086 version of ExcelDataReader in a .NET core project to open an XLS file generated by a web API. However, I've got the following exception when creating the reader : 
`Exception thrown: 'System.NotSupportedException' in System.Private.CoreLib.ni.dll ("No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.")`

I've tried using the `FallbackEncoding` property but without success. Is there a way to read this file ? Send me an email if you wish to have the XLS file, I cannot share it publicly.

**Comment by andersnm** [comment]
Hi,

Before using the reader from a .NET Core application, I believe you need to add a dependency on the "System.Text.Encoding.CodePages" Nuget package, and then register the codepage provider in the application initialisation code (f.ex in Startup.cs):

```c#
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
```

The error message you see comes from when ExcelDataReader initializes the FallbackEncoding property internally, but fails on .NET Core because the codepages aren't registered by default. 

This should be documented in the README, or fixed if possible! The codepages stuff is a difference in .NET Core from the full framework I have not looked too much into yet

**Comment by corenting** [comment]
@andersnm this solution is correct, thanks you ! Adding `System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);` in Startup.cs does solves the problem. Maybe adding a .NET Core part in the README or throwing a more explicit Exception could solve this ?
