### ISSUE TITLE
Excel header and footer (not header row)

### ISSUE THREAD

**Issue by Voggy** [ExcelDataReader/ExcelDataReader#244]
Hi

Is it possible to retrieve data from the Header and Footer of an Excel document?  I've been able to extract data from the rows/columns of the main body of the document but can't find a way to access the header/footer

Thanks

Martin

**Comment by appel1** [comment]
No, but I don't think it would be very difficult to provide the raw text. Interpreting the commands is imo not something that this library can provide. 

@andersnm, we could just add a Header and Footer property to IExcelDataReader as we do with the sheet name and visible state, or do you see any reason to start with some kind of sheet metadata object?

**Comment by andersnm** [comment]
Properties are fine with me.

**Comment by appel1** [comment]
Not so simple after all. In xlsx you can have different headers and footer on the first page and/or on even and odd pages. So I guess we need a class that exposes this instead of multiple properties on IExcelDataReader. 

```
public class XlsxHeaderFooter
{
  public bool HasDifferentFirst { get; }
  public bool HasDifferentOddEven { get; }

  public string FirstPage { get; }
  public string EvenPage { get; }
  public string OddPage { get; }
}
```

Should FirstPage throw if HasDifferentFirst is false? What about HasDifferentOddEven and EvenPage and OddPage? We could mirror Excel and always populate OddPage and throw in EvenPage when HasDifferentOddEven is false or both could have the same value in that case. 

Perhaps simpler to use would be to always populate FirstPage, EvenPage and OddPage and just return the same value for all of them when HasDifferentFirst and/or HasDifferentOddEven  is false. 

Opinions?

**Comment by andersnm** [comment]
Doesn't matter too much, but I think the simplest approach without throwing is preferable as long as the booleans' documentation indicates which strings are valid when. Unused strings could be null too.
