### ISSUE TITLE
Excel 97-2003 cannot be opened using ExcelDataReady:CreateBinaryReader with the following exception:  {"Invalid file signature."}.

### ISSUE THREAD

**Issue by mrefai** [ExcelDataReader/ExcelDataReader#260]
Hello there, 
I am trying using ExcelDataReader to read an old excel 97-2003 with extension ".xls" using MVC 5 and it throw the following exception: {"Invalid file signature."}.
Can you please help and let me know if you like me to share with you the excel file.
Thanks

**Comment by andersnm** [comment]
Hi @mrefai, Yes, if you can share the .xls please do. Alternatively, have you tried using CreateReader() instead of CreateBinaryReader, just to be sure?

**Comment by andersnm** [comment]
Btw, it might help to see your code too. Also check if you are seeking in the stream before calling CreateReader? It expects the current file position to be at the start of the file. I guess this could happen f.ex if using a MemoryStream

**Comment by mrefai** [comment]
Thanks for the quick response,
Actually I tried both CreateBinaryReader and CreateReader. When using CreateReader I am getting the following exception "{"Object reference not set to an instance of an object."}". and btw as you see the below code, I do not use any seek.
And I could not attach the xls file as it is not supported here..I can however email it to if u like..



 protected void ImportXlsExcelReader(HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {                
                Stream stream = upload.InputStream;                
                IExcelDataReader reader = null;
                if (upload.FileName.EndsWith(".xls"))
                {
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    //reader = ExcelReaderFactory.CreateReader(stream);
                }
                else if (upload.FileName.EndsWith(".xlsx"))
                {
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }               
                //reader.IsFirstRowAsColumnNames = true;
                DataSet result = reader.AsDataSet();
                reader.Close();               
            }           
        }

**Comment by andersnm** [comment]
Hi,

Github blocks uploads with filename extensions it doesn't recognize. To upload .xls here, either zip it first, or simply rename the file to .zip.  =)

First make sure you use latest ExcelDataReader 3.1 packages. I cannot quite match your description with the expected behaviour in latest version (I see that `IsFirstRowAsColumnNames` is commented out, which might indicate you are, but please confirm)

Afaik HttpPostedFileBase.InputStream is a forward-only stream, so it cannot be used directly with ExcelDataReader because it uses seeking (ExcelDataReader should have a better error message here!)

Side-point: note that testing for `upload.FileName.EndsWith(".xls")` does not match if the user uploaded a file with ".XLS" extension or similar.

Suggest to read the data into a MemoryStream first, reset the stream Position to 0, then use `CreateReader` to read from the MemoryStream. CreateReader auto-detects the file format without relying on file name extensions

The same code could be written like this: 

```c#
protected void ImportXlsExcelReader(HttpPostedFileBase upload)
{
	if (upload != null && upload.ContentLength > 0)
	{
		var stream = new MemoryStream();
		using (upload.InputStream) {
			upload.InputStream.CopyTo(stream);
		}
		stream.Position = 0;
		
		using (var reader = ExcelReaderFactory.CreateReader(stream)) {
			var result = reader.AsDataSet();
			
			// use result DataTable here
		}
	}
}
```

This is untested, hopefully no typos or wrong assumptions! It could be improved to handle parser errors with a try/catch around the `using (var reader ...)` block

**Comment by mrefai** [comment]
Thank you very much for the help, I tried your code and still having the same exception {"Object reference not set to an instance of an object."}.
I changed the file extension to zip and uploaded it so you can double check.
Thanks again..
[LastSample.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/1203062/LastSample.zip)

**Comment by andersnm** [comment]
It's an .ods :) It's not an Excel file, but probably a renamed OpenOffice/LibreOffice spreadsheet. Alas ExcelDataReader can't read those at the moment.
