### ISSUE TITLE
Only one tab sheet is read

### ISSUE THREAD

**Issue by Ed11** [ExcelDataReader/ExcelDataReader#27]
Hi there, 

I have an Excel file that contains several tab sheets, named like this: HUN-CZE, HUN-FRA, FRA-ENG and so on. I load the file using this code: 

 IExcelDataReader excelReader = ExcelReaderFactory.CreateBinaryReader(stream); 
 DataSet result = excelReader.AsDataSet(); 

 But the resulting dataset contains only one tab sheet, named "Sheet 1". 

 What am I doing wrong? 

 Regards, 

 -Eduardo

**Comment by Namlak** [comment]
I've got a similar problem, I'm receiving sheets recreated by someone else (and I'm not sure what is generating them just yet, just getting stuck on it today) and I can open the excelDataReader and it shows it as valid, yet .Read() always returns false and .AsDataSet() returns a DataSet object with no tables.

Opening and immediately saving via ctrl-s "fixes" the file, just as Ed11 notes above.  Unfortunately, this is for an automation task so doing that is no solution for me.

And, of course, it contains sensitive data but I'm willing to help troubleshoot.  Can even do it live via webex and phone/Skype if that helps.

**Comment by Namlak** [comment]
Update:  After learning *far* more tonight about the Excel Biff format, I see that there are no ROW records in the files I'm receiving, hence the code in excelDataReader falls straight through once it reaches the EOF record.  All the data in these files are done as LABELSST records with column/row indexes.

I'm getting these from another party who's probably generating them out of some mysterious black-box package they're running.  I'll find out tomorrow for sure, but my expectations are low.  :^/

What fun!  Looks like I have some coding to do if they can't properly fix their files.

If anyone else has any input as to the best course of action, I'm all ears!  Maybe you'll think of something more elegant than I'll come up with.

**Comment by Ian1971** [comment]
Ah the biff format. I suppose it's possible that the files are valid biff
but non standard implementation. If excel can read them then it should be
possible for exceldatareader to read them.  Probably non-trivial though.

I am super busy to look at it in detail at the moment.  If there was some
way of getting a de-sensitised document that might make it easier for me to
take a quick look in between moments.

Ian

On 13 Feb 2015 05:44, "Namlak" <notifications@github.com> wrote:
>
> Update: After learning far more tonight about the Excel Biff format, I
see that there are no ROW records in the files I'm receiving, hence the
code in excelDataReader falls straight through once it reaches the EOF
record. All the data in these files are done as LABELSST records with
column/row indexes.
>
> I'm getting these from another party who's probably generating them out
of some mysterious black-box package they're running. I'll find out
tomorrow for sure, but my expectations are low. :^/
>
> What fun! Looks like I have some coding to do if they can't properly fix
their files.
>
> If anyone else has any input as to the best course of action, I'm all
ears! Maybe you'll think of something more elegant than I'll come up with.

**Comment by Namlak** [comment]
Thanks for the reply Ian.  Upon presenting evidence of their unconventional file, they offered to send me xlsx files instead (it would have been nice for them to offer it to begin with!).

So, piece of cake, just switch to the XML reader, right?  Nope, their xlsx files contain a Dimension element with a value of "A1" (instead of A1:BY39000 as it should have been) so I was only getting one column.  Would have worked great if they'd left it out!  It's like they're trying to be a pain!

Maybe an option to ignore the Dimension component can be worked into the XMLReader?

So in the end, I ended up using ClosedXML to open the xlsx file and work the columns and rows manually.  Gotta love the clueless workers here at The Phone Company - "it's opens in Excel so it must be right"....

**Comment by Ian1971** [comment]
I checked the xlsx spec and it does seem that it is not a valid dimension
record. You could also try npoi, to see if that handles the non-standard
dimension record.

Dimension is not required, so perhaps it could be ignored if invalid. That
would probably require some work though.

On Thu, Feb 19, 2015 at 2:17 AM, Namlak <notifications@github.com> wrote:

> Thanks for the reply Ian. Upon presenting evidence of their unconventional
> file, they offered to send me xlsx files instead (it would have been nice
> for them to offer it to begin with!).
>
> So, piece of cake, just switch to the XML reader, right? Nope, their xlsx
> files contain a Dimension element with a value of "A1" (instead of
> A1:BY39000 as it should have been) so I was only getting one column. Would
> have worked great if they'd left it out! It's like they're trying to be a
> pain!
>
> Maybe an option to ignore the Dimension component can be worked into the
> XMLReader?
>
> So in the end, I ended up using ClosedXML to open the xlsx file and work
> the columns and rows manually. Gotta love the clueless workers here at The
> Phone Company - "it's opens in Excel so it must be right"....
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/27#issuecomment-74988610>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by CapCap** [comment]
Experiencing exact same problem with my client as well. Dimension element has a value of "A1", only one column being loaded out of ~15.

**Comment by JYasgar64** [comment]
I have an .xlsx spreadsheet that I actually modified one of the sheets and saved. It still only sees the second sheet. This is using O365 Excel 2013. If I remove the second sheet, it sees none. I'm attaching a test file that has the two sheets. This originally came from a customer. I hope it helps, as for now, we were already in UAT, so now I have to find an alternative.
[TestGoodFileNoData.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/200433/TestGoodFileNoData.xlsx)

**Comment by Ed11** [comment]
Estare fuera de la ciudad del 31 de Marzo al 02 de Abril 
    
    Para cualquier detalle favor de contactar al Ing. Jesus Cruz jesuscruz@akzent.mx
    
    Gracias
    -- 
Eduardo Ãlvarez
Departamento de Sistemas
Arcatek, S.A. de C.V.
Tel.: (867) 715-84-20 Ext. 233
MÃ³vil: (867) 129-70-16
-------------------------------
Aviso Legal 
El contenido de esta comunicaciÃ³n electrÃ³nica no se considera oferta, propuesta, o acuerdo de voluntades, salvo que sea suscrito por firma autÃ³grafa del representante legal de la CompaÃ±Ã­a.  El contenido de esta comunicaciÃ³n es confidencial para uso exclusivo del destinatario, por lo que se prohÃ­be su divulgaciÃ³n total o parcial a cualquier tercero no autorizado. Si usted no es el destinatario, se prohÃ­be su utilizaciÃ³n total o parcial para cualquier fin. 

********************************************************* 
Legal Disclaimer 
The content of this electronic communication is not to be considered as an offer, proposal, or agreement unless it is confirmed in a document duly signed by the Company's legal representative. The content of this communication is confidential and for the exclusive use of the addressee. Its total or partial disclosure to any unauthorized third party is strictly forbidden. If you are not the addressee you are forbidden to use it, either totally or partially, for any purpose.
*************************************
Akzent, S.A. de C.V., con domicilio en Ricardo Margain Zozaya 335, Col. Santa Engracia, en la ciudad de San Pedro Garza GarcÃ­a, Nuevo LeÃ³n, le informa que los datos personales y profesionales proporcionados por usted, ya sea en lÃ­nea o vÃ­a telefÃ³nica, estÃ¡n siendo utilizados para cumplir con la relaciÃ³n jurÃ­dica que nos pudiera vincular; informarle de nuestros servicios; hacerle llegar comunicaciones y/o contactarlo.  
Para mayor informaciÃ³n escrÃ­banos a: privacidad@akzent.mx

**Comment by wizardgsz** [comment]
Maybe you "cut" too data preparing test-case: the two Sheets contain same information as the header, nothing more to compare... Could you leave the first Row of data at least?

**Comment by JYasgar64** [comment]
That's my test case, a spreadsheet with only header. I'll see on Monday if it having no rows other than the header is what's causing it.

**Comment by wizardgsz** [comment]
Anyhow, taking a look at `ReadWorkbook `and `ReadWorkbookRels`...

Your data contains, Workbook as:
```
<sheets>
	<sheet r:id="rId1" sheetId="2" name="Sheet2"/>
	<sheet r:id="rId2" sheetId="1" name="Sheet1"/>
</sheets>
```
Relationships as (omitted Type info):
```
<Relationship Target="worksheets/sheet2.xml" Type="..." Id="rId2"/>
<Relationship Target="worksheets/sheet1.xml" Type="..." Id="rId1"/>
```
In `ReadWorkbook` the Library prepares two `XlsxWorksheet`, reading rels then (see `ReadWorkbookRels`):

- sheet[1] has Id=rId2 and its file is worksheets/sheet2.xml
- sheet[0] has Id=rId2 and its file is worksheets/sheet2.xml (same as above)

**Comment by JYasgar64** [comment]
Hi wizardgsz, 

Thanks for taking a look at this so quickly!

Yes, column headers is on. I know I've only been writing code for 26 years, but it seems that having sheets dropped because they don't have any rows would be problematic for most processing. :-) (Your post sounds like you feel this is expected behavior) 

I ran through some tests this morning. I created a blank file with header row only. Sees no tables, created a second tab with only header, sees zero sheets. So it appears that it is just dropping sheets that have no rows outside of the header row.

I did some other tests, but eventually, the code sees both sheets. I imagine because the row is there, it is just empty. I'm not creating these files, so I don't have any control over what order sheets are in. I need to be able to see sheets, whether they have rows or not.

* Headers on both sheets, only data on second sheet - Only sees second sheet
* Take WB that fails, with no data in sheet 1 - added one row, now sees both sheets
* Leave headers on second sheet, move both data lines to first sheet, sees both sheets (still has blank rows)
* Took both lines of data, moved back to sheet 2, now sees both sheets

* Took new copy of sample file
* Deleted second sheet, sees zero sheets
* Added some data to sheet 1 in row 2, sees sheet 1
* Removed data from sheet 1, sees zero sheets.

* Took new copy of sample file
* Moved data from sheet 2 to sheet 1, sees two sheets

Thanks!

**Comment by wizardgsz** [comment]
If you need to "keep" sheets without rows (except for header), you can modify readers.
Take a look at `AsDataset(bool)` and remove the check:
```
if (table.Rows.Count > 0)
    dataset.Tables.Add(table);
table.EndLoadData();
```

**Comment by wizardgsz** [comment]
Is your issue solved @JYasgar64?
Regards

**Comment by JYasgar64** [comment]
Yes, thank you very much @wizardgsz

**Comment by MoosHam** [comment]
I have the same issue as Namlak, Wrong DIMENSION: A1. I also have no influence on the way the files are created.
Problem is: If is has A1 as a Dimension, it will ONLY read column 1 (A) and ignore the other column. After opeing and saving it in Excel, it works. But this is no solution for my program though.

**Comment by wizardgsz** [comment]
Please, try reading the following [bug](http://bz.apache.org/bugzilla/show_bug.cgi?id=53611) of POI/NPOI.
Maybe you can apply the same workaround if you have "fixed" dimension.
Anyhow, I can't understand which file format are you referring to (XLS BIFF or Open XML).

[Bug 53611 - Incorret dimension set in created workbook sheet xml file ](http://bz.apache.org/bugzilla/show_bug.cgi?id=53611)

**Comment by MoosHam** [comment]
@wizardgsz : It is related to XLSX Files (if that's what you mean). 

Unfortunately these Files are supplied via a legacy application which I cannot change nor have access to. I Can open the files using the Interop Method via Excel, but this is slow, considering that my program has to process many of them.
Good to know that this is a Bug in POI/NPOI, very likely that the developer used this for his application.

Is there anything that can be done within ExcelDataReader? Maybe have an extra switch, telling it to ignore the dimension?

Unfortunately I am not proficient in C#. I tried to play around with the Code, but was not able to compile it (something about my Visual Studio not being supported).

**Comment by wizardgsz** [comment]
Well, as workaround you can just use Interop to get the correct DIMENSION record(s), then you'll read the file using ExcelDataReader Library. This way you still have the speed offered by the Library (together with the right implementation of Microsoft Excel).

To compile the Library you can use VS 2012 (or above) but I can't help you configuring it.

**Comment by MoosHam** [comment]
it took me a while to figure this out, but it seems I cannot compile this because one Project is a "portable library". This kind of project is not compatible with Visual Studio Express 2015 which I am using. So seems I cannot get it to csompile.

But as I have read about this Dimension Issue, wouldn't it be a generally helpful setting in the library to be able to override the usage of DIMENSION? I would be very thankful if someone could build this in :-)

**Comment by wizardgsz** [comment]
So, if you can't use neither develop-branch nor latest .NET Core package, I suggest to download and work on the old [CodePlex](http://exceldatareader.codeplex.com/) repository (it did not use PCL library).
As soon as you'll find a solution, we will apply it to the latest build here.

Thanks a lot for your help in solving this issue.

**Comment by MoosHam** [comment]
@wizardgsz : Thanks for your advise, this did the trick! .NET Core did not work, I guess the same thing about using the EXPRESS Version. Unfortunately the error message are misleading at best.

BUT: Using the old code from CodePlex did Work! I found the spot (in Excel\ExcelOpenXmlReader.cs) where to tell the code that there is basically No Dimension Value (null) so it went and checked the columns itself. Works like a charm and together with the EDRHelper I can read my Excel Files with 2 lines of code in a Split second, rather than in about a second with the Interop way. HUGE improvement.

Thanks again! it really was helpful. Do you think this would be something worth getting into the "official" code, or is this too specific?

**Comment by wizardgsz** [comment]
Oh, really fine!
Where and how did you change the reader to fix this issue?

**Comment by MoosHam** [comment]
It is more of an hack, don't know enough of the code to say what it breaks :-)

in the file Excel\ExcelOpenXmlReader.cs around Line 130:
in "private void ReadSheetGlobals(XlsxWorksheet sheet)" in the "while (_xmlReader.Read())" loop
I commented out / changed these 2 lines:
```
                    sheet.Dimension = null;// new XlsxDimension(dimValue);
					//break;
```

**Comment by wizardgsz** [comment]
Ok, and your input XLSX has something like this in DIMENSION tag:
`<dimension ref="A1:A1"/>`

or maybe 
`<dimension ref="A1"/>`

What's the value of `dimValue` loading your file?
`string dimValue = _xmlReader.GetAttribute(XlsxWorksheet.A_ref);`

We haven't your test case (see xl\worksheets\sheet###.xml).

**Comment by MoosHam** [comment]
The Dimenson is given as A1, although the range "A1:AX4" is filled with data.

This is how the file starts:
`<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1"/>`

[sheet1.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/403662/sheet1.zip)

**Comment by Snoopy-dogg** [comment]
Is there some way to get columns widths in ExcelDataReader? I can find only row height.
