### ISSUE TITLE
[Feature request] Support .xlsb (Excel Binary Workbook)

### ISSUE THREAD

**Issue by askovpen** [ExcelDataReader/ExcelDataReader#275]
.xlsx loads 4 times longer than .xlsb and saves 2 times slower and has 1.5 times a bigger file. Reportedly a user from leading forums Stackoverflow tested this on a generated worksheet with 10’000 rows * 1’000 columns = 10’000’000 (10^7) cells of simple chained =…+1 formulas:

| |.xlsx |.xlsb |
|--------------|--------|---------|
| loading time | 165s | 43s  |
| saving time | 115s | 61s |
| file size | 91Mb | 65Mb |

**Comment by andersnm** [comment]
Reference:
https://msdn.microsoft.com/en-us/library/cc313133(v=office.12).aspx

Somebody started on xlsb support many years ago, but was removed during the big "3.0 cleanup" last year because it was incomplete and unused:
https://github.com/ExcelDataReader/ExcelDataReader/tree/c3b50c73b981a010d90b4027a04d2b0c33cc6ee8/Excel/Core/Binary12Format

I doubt this will be implemented in the near term, unless somebody wants to help out. It would be a nice addition to the library. I consider it a fun/interesting task of intermediate difficulty level (also we have all the infrastructure to read password protected xlsb)

**Comment by kendallb** [comment]
Interesting, when did this file format get added to Excel? I just noticed it is in my Office 2016 release but I have personally never seen such a file in the wild. The normal .xslx format is certainly compressed already, but it is just compressed XML I think, not binary and was usually smaller than the old .xls BIFFx formats. 

Would be interesting to see it supported, but I wonder how often it would get used?

**Comment by ltrinca** [comment]
Hi, I'm trying to use the ExcelReaderFactory.CreateBinaryReader to read a binary file (xlsb) and I'm getting the exception message "ExcelDataReader.Exceptions.HeaderException: 'Invalid file signature.'"

Any suggestions to fix this error?

Tks

**Comment by sauravkarna** [comment]
Has anyone worked on this?
ExcelDataReader is working great with ".xls", ".xlsx" and ".csv" formats, but I had to use other readers just because it couldn't use ".xlsb" format.
Will be of great help if this feature was added. 

Thanks

**Comment by jerryjoseph-net** [comment]
> Hi, I'm trying to use the ExcelReaderFactory.CreateBinaryReader to read a binary file (xlsb) and I'm getting the exception message "ExcelDataReader.Exceptions.HeaderException: 'Invalid file signature.'"
> 
> Any suggestions to fix this error?
> 
> Tks

As I understand ExcelReaderFactory.CreateBinaryReader() cannot handle xlsb files as of now.

**Comment by appel1** [comment]
I'm working on this and have a rough implementation. Have a few things to fix that I'm hoping to get done next week before creating a pull request.
