### ISSUE TITLE
TimeSpan not supported and read as DateTime?

### ISSUE THREAD

**Issue by kendallb** [ExcelDataReader/ExcelDataReader#283]
Hi Guys,

I am in the process of re-writing my ExcelHelper code to use ExcelDataReader so it can read older BIFF8 and earlier format files. I have run into a snag with TimeSpans. The CloseXML library which I have been using to generate the test data to test against natively supports reading and writing TimeSpan values and it stores them in the file as a string with the format type of 46:

https://github.com/ClosedXML/ClosedXML/wiki/NumberFormatId-Lookup-Table

https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/Cells/XLCell.cs#L227

However when that is ready by ExcelDataReader, it reads the value back as a DateTime object, not a TimeSpan? I can probably detect this scenario in my conversion code and handle it, but it would seem better for ExcelDataReader to recognize this as a TimeSpan and actually return it as such?

I would be happy to write the code for this and generate a PR (got to get VS2017 installed first), however I don't know if this would cause a breaking change for anyone who might have relied on TimeSpan values with formatId 46 being parsed as DateTime values?

**Comment by appel1** [comment]
Isnt 46 a date and time formatted as time, [h]:mm:ss? Don't think we should change the meaning of that as we try to interpret things the same as Excel. 

That said, there's been an idea to expose the format information and raw values that should enable you to interpret it however you want. See #215.

**Comment by kendallb** [comment]
It is stored as a date but in reality the the intent of the [h]:mm:ss format is to allow times longer than 24 hours to be stored so it actually correctly handles native time spans. Since that format can’t actually be correctly represented as a DateTime in .net (due to going more than 24 hours or more than 31 days) if you do load it with ExcelDataReader you end up with the day portion becoming the day of the year. So it becomes a non-sensical DateTime value and a TimeSpan is actually a much better and more usable representation for .net code.

I suspect that is what the ClosedXML project loads and saves TimeSpan values when it sees that rather than a DateTime. I suspect it is a better way to represent it for this project also.

https://support.microsoft.com/en-us/help/266691/how-to-sum-and-format-a-range-of-hours--minutes--or-seconds-in-excel

**Comment by andersnm** [comment]
If a number format contains [hh], [mm] or [ss] its an "Elapsed time" type format, which indeed maps very well to a .NET TimeSpan. I agree it is a good idea to support TimeSpans natively, but I also agree this is a breaking change =)

Afaik ExcelDataReader currently returns these values as DateTimes relative to January 1 1900, so technically you could derive TimeSpans from them, but not 100% reliably since the original formatting is lost.

In the short term, I think the work planned in #215 can provide for a workaround if it exposes a number format object with properties such as `IsTimeSpanFormat` and `IsDateTimeFormat`.

A future version 4.0 could/should implement `IExcelDataReader.GetTimeSpan()` directly.

**Comment by kendallb** [comment]
Yes, the solution I took for my project was to simply convert the DateTime to a TimeSpan, but as you say the original formatting is lost so you can’t get the native value and ToString() it and get anything sensible out.

My latest code using ExcelDataReader is now up on GitHub and NuGet here:

https://github.com/kendallb/ExcelHelper

I will take a look at #215

**Comment by kendallb** [comment]
Crap how do I unclose this? I clicked the wrong button. Lol

**Comment by andersnm** [comment]
Hmm, because timespans are considered dates, their underlying double/int representation undergoes the same fixing as all dates:  in most cases, values between 0-60 (days) are adjusted for the "1900 leap year bug in Excel", in other files (mac), the values are adjusted by 1462 days to account for "1904 dates".

But it sounds like timespans might be stored as absolute values which are often below 60 days, and shouldn't be fixed like this by the reader. I'm wondering if this is why you say can't get anything sensible out? Do you have an example of an unreasonably parsed timespan DateTime handy?

**Comment by kendallb** [comment]
Well my test values seemed to come out correctly when I converted from a DateTime to a TimeSpan. When I said a sensible date I meant that it parses correctly but the resulting date does not really mean anything when the value was intended to be a timespan? So I was still able to get it to work but not 100% in ExcelHelper like this:

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper/TypeConversion/TimeSpanConverter.cs#L42

That seems to work as long as you don't try to format the incoming data as a string, as then it formats it as a DateTime, not a TimeSpan.

I have not dug too closely into how the data is ready via ClosedXML, but when I was using that for the reading it was able to correctly import TimeSpan values as TimeSpan's. Maybe I will debug into that more.

At this point I cannot do any real work on this library as I do not yet have VS2017 installed. Might do that this week.

**Comment by kendallb** [comment]
This is the unit test I had to comment out at the moment that used to work with ClosedXML (and also I believe the C1.Excel library we used to use):

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper.Tests/ExcelReaderTests.cs#L137

**Comment by andersnm** [comment]
In your case, when you expect a TimeSpan, the code should do something like:

```C#
	// ExcelDataReader reads TimeSpans as DateTime values
	var dt = (DateTime)excelValue;
	return dt - new DateTime(1900, 1, 1); // subtracting two DateTime returns a TimeSpan
	// return new TimeSpan(dt.DayOfYear, dt.Hour, dt.Minute, dt.Second, dt.Millisecond);
```

Am curious if this works, apparently we have no unit tests for timespans :)

**Comment by andersnm** [comment]
Heres some data with timespans and datetimes where the underlying values are near zero, and around where the leap year bugfix triggers:

Example from Excel:

FmtId 46|[hh]:mm|Date|Underlying value
-|-|-|-
0:00:00|0:00|1/0/1900 0:00:00|0.00
24:00:00|24:00|1/1/1900 0:00:00|1.00
1392:00:00|1392:00|2/27/1900 0:00:00|58.00
1416:00:00|1416:00|2/28/1900 0:00:00|59.00
1440:00:00|1440:00|2/29/1900 0:00:00|60.00
1464:00:00|1464:00|3/1/1900 0:00:00|61.00

Same in ExcelDataReader:

FmtId 46|[hh]:mm|Date|Underlying value
-|-|-|-
12/31/1899|12/31/1899|12/31/1899|0
1/1/1900|1/1/1900|1/1/1900|1
2/27/1900|2/27/1900|2/27/1900|58
**2/28/1900**|**2/28/1900**|**2/28/1900**|**59**
**2/28/1900**|**2/28/1900**|**2/28/1900**|**60**
3/1/1900|3/1/1900|3/1/1900|61

There is at least one issue in ExcelDataReader here. It makes sense to fix this as a bug by introducing TimeSpans natively for values whose formatting contains [hh], [mm] or [ss]. That means there is a chance of breakage for some users, but then again: it never worked properly anyway.. (?)

**Comment by kendallb** [comment]
Interesting. I had no idea Excel had that bug in it. I do wonder how many people would have been reading these values using DateTimes from when they were TimeSpan in excel since what they got might not be what they expected anyway.

**Comment by andersnm** [comment]
@appel1 What are your thoughts? Does it make sense to implement support for TimeSpans as a bugfix in a minor 3.3 release? Now that most of #215 is in place, it is relatively easy to fix.

According to semver.org:
```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

I'd say this is an edge case between MAJOR and MINOR version bump, since it adds functionality in a *mostly* backwards-compatible manner, but changes the API behavior of something that didn't work. And possibly isn't used much. =)

(Am somewhat reluctant of going to 4.0 just for this, was hoping for 3.x to gain more features and mature a bit longer, and then we could refactor and break stuff)

**Comment by appel1** [comment]
@andersnm I think we should fix this since what we currently return is wrong. The number of users that rely on the current behavior is hopefully low.

**Comment by kendallb** [comment]
Cool. When will this make it into the NuGet package so I can try it out? Still have not installed VS2017 ...

**Comment by kendallb** [comment]
BTW, slightly unrelated question, but does Excel preserve a date's timezone when it is saved to disk and retrieved? Or are they always assumed to be in local time?

**Comment by andersnm** [comment]
These Nugets are probably very close to the final release - not sure when I'll get around to do the release:

https://ci.appveyor.com/project/andersnm/exceldatareader/build/build-152/artifacts

Do you have a chance to confirm if the TimeSpan support works for you?

As far as I can tell there is no timezone info in the Excel files, at least not per the XLS spec.

**Comment by kendallb** [comment]
I have not had a chance to try it out yet but now I see some beta NuGet packages I might give it a try this weekend for the TimeSpan support.

And yes, as far as I can tell the dates in Excel files are unspecified for the timezone so treating them as local time or UTC is up to the application consuming the data.
