### ISSUE TITLE
worksheet name contains a dot

### ISSUE THREAD

**Issue by gilyoktan** [ExcelDataReader/ExcelDataReader#303]
Hello
The application failed because I had a dot in the worksheet name - like "book 1.1"
how can I change the worksheet name after opening the xls file?
Thanks in advance   Gil Yoktan

**Comment by andersnm** [comment]
Hi!

Do I understand correctly if ExcelDataReader works for you, but you need to rename the imported sheets for some other code to work?

If so, assuming you are using AsDataSet(), you may have success looping over the DataTables and removing any dots in their TableName property:
https://msdn.microsoft.com/en-us/library/system.data.datatable.tablename(v=vs.110).aspx

If the problem is more sinister than that, f.ex if ExcelDataReader crashes, can you please show us the code that fails, with a stack trace, and attach the .xls file that fails to load? (you need to zip the .xls or rename to .zip for github to accept the upload!)

**Comment by gilyoktan** [comment]
Thanx a lot – your solution did it. I tries from the reader (before “asDataSet”) – the worksheet name is read-only…
But dataset.tables did it
Thanks again – for this help and for your exceldatareader


Have a nice day         יום נעים
Gil Yoktan  -  Tadiad - SMB Dpt
04-8273671
054-4853320
Fax 04-8273675
תדיעד  ד. נ. אשרת 25201
Tadiad - DN Oshrat 25201 Israel
