### ISSUE TITLE
AutodetectSeparators = new char[] { ',', ';', '\t', '|', '#' } is not working if defined all in csv file

### ISSUE THREAD

**Issue by Nirmalsharma4u** [ExcelDataReader/ExcelDataReader#360]
When using AutodetectSeparators = new char[] { ',', ';', '\t', '|', '#' } it not automatically detect separator but when using AutodetectSeparators = new char[] { ',' } 
or AutodetectSeparators = new char[] {  '\t' } 
it detects and work separate data as needed.
I need to add AutodetectSeparators = new char[] { ',', ';', '\t', '|', '#' } to detect separator automatically and parse data as per separater. Or to detect the separator and add to the character and use it as AutodetectSeparators = new char[] { '' }
For reference i have attached file.
[testfile.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/2483222/testfile.zip)

**Comment by jakubmaguza** [comment]
Separator will be detected as one of characters you have in this array. If you will put only one char there, this will be your separator. If you will put more than one character, it will be detected by calculating avg number of fields in your set. If every line got the same number of fields, separator will be detected properly. If your file could have f.e. 2 fields in first line and 10 fields in second line, I will recommend to leave only one character in this array, so you will be sure that is correct one. Also it will be little bit faster :)

**Comment by andersnm** [comment]
Hi, the attached testfile.csv works as expected with the default separators { ',', ';', '\t', '|', '#' }. Did you attach the correct file?

![testfile](https://user-images.githubusercontent.com/16575282/47022822-9d3dbc80-d15e-11e8-90e2-d6be2e8137f0.png)

**Comment by Nirmalsharma4u** [comment]
Hi, I have attached new file  can you please try on this file its not working.
[2_9_1 (2).zip](https://github.com/ExcelDataReader/ExcelDataReader/files/2483720/2_9_1.2.zip)

**Comment by andersnm** [comment]
Ok, thanks for the new test file. So tab wins as the separator, despite there being only one tab in the entire file. It's definitely an indicator the current autodetection algorithm isn't entirely sound.

The following table lists the internal results of the analyzer after parsing the file with each of the separators. AvgFields is (TotFields/RowCount), and Distance is (MaxFields-AvgFields), and lowest distance wins:

|Separator|MaxFields|TotFields|AvgFields|RowCount|Distance|
|---------|--------:|--------:|--------:|-------:|--:|
|,        |       42|      910|     33.7|      27| 8.3|
|;        |       14|      123|      4.6|      27| 9.4|
|\t       |        2|       28|     1.04|      27|0.96|
|(pipe)   |        1|       27|        -|      27|   -|
|#        |       14|      131|      4.9|      27| 9.1|

(The pipe is skipped because MaxFields=1, meaning the separator didn't occur)

Not sure how to improve this yet, open for any ideas =)

**Comment by jakubmaguza** [comment]
This file is strange. Is not 'normal' '.csv' file. IT has few files inside. I belive in those cases, separator should be set manualy. Only thing I can think of in this case is to check if separator appears in most of lines, so it will exclude \t scenario.
