### ISSUE TITLE
UseColumnDataType Not Working

### ISSUE THREAD

**Issue by iferb** [ExcelDataReader/ExcelDataReader#394]
Hi! I have a problem with a type "TEXT" in Excel.

When i write a value like 12345 (is an string), the library ExcelDataReader come the column type in decimal

Here is my code
```
using (var stream = new FileStream(pathFile.fisicalPath + filePath, FileMode.Open, FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        //Excel to dataset
                        var resultDataSet = reader.AsDataSet(new ExcelDataSetConfiguration()
                        {

                            UseColumnDataType = false,
                            ConfigureDataTable = (tableReader) => new ExcelDataTableConfiguration()
                            {
                                // Gets or sets a value indicating whether to use a row from the 
                                // data as column names.
                                UseHeaderRow = true,

                                // Gets or sets a callback to determine which row is the header row. 
                                // Only called when UseHeaderRow = true.
                                ReadHeaderRow = (rowReader) => {
                                    // F.ex skip the first row and use the 2nd row as column headers:
                                    rowReader.Read();
                                },
                            }
                        });
                        
                        DataTable table = resultDataSet.Tables[0];

                        string json = JsonConvert.SerializeObject(table, Formatting.None, new JsonSerializerSettings { });

                        listPost.Add(json);
                    }
                }
```

When I convert the datatable in JSON, the value's result is 12345.0
I think that the problem is the column type

Note: With .CSV the error does not exist.

**Comment by andersnm** [comment]
Hi,

Could you also attach the Excel file please?

**Comment by andersnm** [comment]
Hi,

I tested three different ways to use text in Excel, and how it's returned by ExcelDataReader:

Value| ExcelDataReader type | How
-- | -- | --
1234 | string | Using quote: '1234
1234 | string | Using TEXT(1234, "0")
1234 | double | Applied number format "Text" on a number value

Both xls and xlsx have the same behavior.

So you're likely hitting that third option. I guess one could argue the current behavior is either right or wrong, depending on the use case. A workaround could be to use the reader APIs and the GetNumberFormatString() method, and check if the value should be text or not.

**Comment by iferb** [comment]
[Plantilla Localidades.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/2885262/Plantilla.Localidades.xlsx)

Here is the file, thanks

**Comment by iferb** [comment]
> Hi,
> 
> I tested three different ways to use text in Excel, and how it's returned by ExcelDataReader:
> 
> Value	ExcelDataReader type	How
> 1234	string	Using quote: '1234
> 1234	string	Using TEXT(1234, "0")
> 1234	double	Applied number format "Text" on a number value
> Both xls and xlsx have the same behavior.
> 
> So you're likely hitting that third option. I guess one could argue the current behavior is either right or wrong, depending on the use case. A workaround could be to use the reader APIs and the GetNumberFormatString() method, and check if the value should be text or not.

Thanks for the fast response.

The Repsonse in the datatable is ok, but does not respect the datatype of the column.
The datatype of the column in my excel file is TEXT, but in the datatable the column type is Decimal.

When i convert the datatable to json, tghe response is 12345.0, because the datatype is distinct from the original.

**Comment by andersnm** [comment]
Hi,

Thanks for the example file. I notice the values in the three columns "Equivalente", "Código Postal" and "Teléfono" have numbers in them with the "Text" number format. This matches the third option in the above table indeed.

Technically, those values are saved in the spreadsheet XLSX file as a double/decimal datatype, but Excel formats them as text via the "Number Format" feature. This formatting is applied by Excel when the spreadsheet is displayed on screen, but actually uses the double datatype behind the scenes to hold the cell value.

ExcelDataReader extracts and returns the raw values that are stored in the file, which is why these become f.ex 12345.0 in the JSON. ExcelDataReader does not apply any formatting.

I don't think we should fix this in ExcelDataReader, because it is mainly a formatting problem: When converting numbers to text via the number format, there are additional complexities: f.ex the number format can specify prefixes and postfixes, and depends on culture specific decimal separator if the number has decimals.

There is however a third party library which does this, and can be used together with ExcelDataReader, called ExcelNumberFormat:
https://github.com/andersnm/ExcelNumberFormat

The ExcelNumberFormat library was made specifically to handle formatting of Excel values when you need an output that matches what is displayed by Excel.

Unfortunately ExcelNumberFormat does not work with AsDataSet(), so you would have to use the reader APIs directly. Also it returns only strings, which may or may not be acceptable depending on your use case. There is a proposal at https://github.com/andersnm/ExcelNumberFormat/issues/8 which should include your use case.

**Comment by iferb** [comment]
Thans for the answer and the info.

I unsdersrtand the case. I tried with a .csv file and the problem does not exist.
I will use it format.

**Comment by mertsalov-re** [comment]
Hi everyone, quite interesting topic! I come across to difficulties when try to read columns with int and DateTime. ExcelDataReader contains methods like GetSting, GetInt32 or GetDateTime (according discription). However, the exception comes out when I read DateTime column in excel with GetDateTime(col index).
Do you have an idea how to read date or DateTime?

**Comment by andersnm** [comment]
Hi @mertsalov-re,

Assuming latest version of ExcelDataReader, and GetDateTime() throws an exception, then your spreadsheet likely does not contain a proper date in the cell you are attempting to retrieve. F.ex it could be a number, string or empty instead.

In those cases you'd typically need to check the type of the cell using the reader's GetFieldType(index) method, or by using GetValue(index) and then calling GetType() on the returned object and compare to typeof(DateTime). F.ex:

```c#
DateTime? mydate = null;
object tmp = reader.GetValue(i);
if (tmp?.GetType() == typeof(DateTime)) {
    mydate = (DateTime)tmp;
}

Console.WriteLine("Date from excel: {0}", mydate);
```

(beware, code is not tested; and should probably be in a helper function)
