### ISSUE TITLE
No rows in table

### ISSUE THREAD

**Issue by m1zun0** [ExcelDataReader/ExcelDataReader#401]
Hi

Having trouble reading attached xlsx file as a DataSet.
No exceptions are thrown, there is a single table with name matching sheet in the output DataSet. However, the table is empty.

                string local = "C:\\temp\\HSRT.xlsx";
                  
                using (var fs = File.Open(local, FileMode.Open, FileAccess.Read))
                {
                    using (var reader = ExcelReaderFactory.CreateReader(fs))
                    {
                        DataSet result = reader.AsDataSet();
                        return result.Tables[sheet];
                    }
                }

Any guidance on how to diagnose would be appreciated.

[HSRT.xlsx](https://github.com/ExcelDataReader/ExcelDataReader/files/3039676/HSRT.xlsx)

**Comment by m1zun0** [comment]
I have also tried skipping first 13 rows which have some merged cells.
Tabular data starts on row 14 but I get same result - nothing in output table.

**Comment by andersnm** [comment]
Thanks for the report and repro!

This looks to be a regression in ExcelDataReader 3.5.0 with the recently introduced column widths parsing. Downgrading to 3.4.1 should help you to progress.

Problem is the XML looks like this:
```xml
<cols><col min="1" max="1" customWidth="1" width="11.8125"></col>...
```

But the reader expects XML like this:
```xml
<cols><col min="1" max="1" customWidth="1" width="11.8125"/>...
```

I think the fix is to replace xmlReader.Read() with xmlReader.Skip() here (and possibly elsewhere):
https://github.com/ExcelDataReader/ExcelDataReader/blob/b9c44e48fba83c3cb6c481f0ff14d91603c94ff8/src/ExcelDataReader/Core/OpenXmlFormat/XlsxWorksheet.cs#L361

**Comment by m1zun0** [comment]
Thank you!! That worked.
Very much appreciate fast response.
Thanks again.
