### ISSUE TITLE
File with images not load (version 5.0/95)

### ISSUE THREAD

**Issue by fs-vladimir** [ExcelDataReader/ExcelDataReader#411]
Return zero rows from this file (if it contains images). May fix this? Images don't need.

[Test.zip](https://github.com/ExcelDataReader/ExcelDataReader/files/3182808/Test.zip)

**Comment by wizardgsz** [comment]
Please, update your version of Excel/Office and save the file again. The file uses the old Excel 5.0/95 format.
I am able to open if using Excel 2003 "save as" feature.

**Comment by fs-vladimir** [comment]
Contragent send this file to me from internal program. And I want processed in auto mode without manual operations.

**Comment by andersnm** [comment]
Hi, thanks for the XLS file!

This is an interesting one. There are both "Book" and "Workbook" CFB substreams in the file, and ExcelDataReader currently picks the "Workbook" if it exists. But in this case all the data is in the "Book", whereas "Workbook" consists only of three empty sheets.

This line must be replaced with a loop looking up the first matching substream:
https://github.com/ExcelDataReader/ExcelDataReader/blob/e5b7d41b580603c866b9097496139080c0bba105/src/ExcelDataReader/ExcelReaderFactory.cs#L190

However, when changing to parse the "Book" substream, the strings come out with wrong encoding:

![image](https://user-images.githubusercontent.com/16575282/57794508-14165480-7744-11e9-93f4-de520e2fa340.png)

This needs further analysis, but is less worrying than the first part of the issue. I will thus leave this for now.

**Comment by andersnm** [comment]
As a follow up to the initial analysis and the second problem;

It was puzzling the file lacks a CODEPAGE record, yet Excel and Google Sheets are able to detect the Cyrillic encoding. Turns out the BIFF5-8 FONT record contains a flag indicating the character set used for byte strings, which is ignored by ExcelDataReader. Have verified this file's FONT records indeed use the Cyrillic identifier, so I suppose this is a hole in ExcelDataReader's support for international characters in BIFF5-BIFF8 XLS.

At the minimum, a fix should parse the font records, map the font character set identifiers to encodings, add fonts to the XF stuff, and then use the font encoding (if specified) when reading byte strings in cells.

Ideally there should be tests for multiple character sets, and for the font indexing scheme where font indexes 0..3 are 0-based, but >4 are 1-based!
