### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by rgruebel** [ExcelDataReader/ExcelDataReader#425]
When I read the value of a cell, the result string is filled with trailing whitespaces until it has the same length as the maximum of the whole column. 
Is this the expected behavior?

**Comment by andersnm** [comment]
Hi,

This is not the expected behavior, unless there are actually spaces in the cells. Any chance to attach a file for repro? (assuming its an xls, please zip it first, otherwise github wont accept the upload)

If you cannot share the file, if would be somewhat helpful with a hex dump of the first 8 bytes of the file, and the bytes before and around a string in the file which is being returned with trailing whitespace

**Comment by rgruebel** [comment]
Thank you for the quick response. When I open the file with Excel there are no spaces. As soon as I make a change to the original file, the spaces also disappear during import. It's an xlsx file, so I unpacked it and the spaces are already contained in the XML. So I think it's not a bug of ExcelDataReader. I just wonder why the spaces are not present when I open the file with Excel.
```
<x:c s="0" t="str">
    <x:v>SHR-ZYL-DIN84-MS-M3X16                  </x:v>
</x:c>
```

**Comment by andersnm** [comment]
Curious. If I create an XLSX with spaces, its saved to the shared string table like this, and the spaces are preserved upon save and reload:

```xml
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1">
  <si>
    <t xml:space="preserve">                 asdad a                      </t>
  </si>
</sst>
```

Sounds like ExcelDataReader could implement support for the special "xml:space" attribute to handle this perfectly, and trim by default if its omitted. Backlog material :-)
