### ISSUE TITLE
AsDataSet() configuration options UseColumnDataType not working

### ISSUE THREAD

**Issue by fieldmarshals** [ExcelDataReader/ExcelDataReader#446]
UseColumnDataType in AsDataSet() configuration options doesn't work if set to False.
Even if set to False, the data will be imported with Column DataType True.

**Comment by andersnm** [comment]
Hi,

Pretty sure it works as intended. It's used here:

https://github.com/ExcelDataReader/ExcelDataReader/blob/774b585973ff11fa7367fad1a0f82d9d02f4f47b/src/ExcelDataReader.DataSet/ExcelDataReaderExtensions.cs#L53-L56

And FixDataTypes is pretty much unchanged since before my time:

https://github.com/ExcelDataReader/ExcelDataReader/blob/774b585973ff11fa7367fad1a0f82d9d02f4f47b/src/ExcelDataReader.DataSet/ExcelDataReaderExtensions.cs#L169

Do you have some examples/screenshots of what you get vs what you expect?

**Comment by fieldmarshals** [comment]
ok for example i am searching a string in datatable where the data is imported from xlsx. However i am getting a error stating "Unable to perform string operations because the column datatype is datetime".

**Comment by andersnm** [comment]
I suspect this is something else. What are you using to search the datatable? That error has no hits in search engines, so it could as well be an imprecise error message upon encountering datetimes in the data.

**Comment by fieldmarshals** [comment]
ok my bad sorry for the trouble, i thought it differently

**Comment by gojimmypi** [comment]
It is unfortunate that this issue was marked as closed, as I am seeing exactly this behavior: data types on the items even when `UseColumnDataType` is set to false. Here's a runtime inspection of dataset `ds` just after reading:

![image](https://user-images.githubusercontent.com/13059545/103236647-3e595d80-48fa-11eb-8fff-6f87833259ba.png)

This is important to me as I need to next convert a large dataset to XML. The datatypes add a massive amount of unnecessary text. Admittedly, I'm using a somewhat old version - the most recent "stable release" presented in Visual Studio 2019 NuGet Package Manager 3.6.0 from May of 2019, but also a version months _prior_ to the comment above from @andersnm that it should be working.

![image](https://user-images.githubusercontent.com/13059545/103236847-ce97a280-48fa-11eb-8515-2a9dc080949e.png)

I believe I am using the sample code properly. Any suggestions on a dataset without types would be greatly appreciated. :)

**Comment by andersnm** [comment]
Hi @gojimmypi,

FYI the values you've highlighted are of type `object` in the code. The debugger is able to derive and show their underlying type, and isn't really related to the `UseColumnDataType` flag.

The `UseColumnDataType` flag controls whether `dataTable.Columns[...].DataType` is populated, which comes from the list of columns defined on the DataTable rather than the individual values' types.

By the way, if performance is important, you shouldn't use `AsDataSet` at all, it is effectively just another layer of looping over the data.

**Comment by gojimmypi** [comment]
Hi @andersnm,

First - I want to thank you for you work on this Excel DataReader. It is an impressive work & has been tremendously helpful to me. It is vastly better than the `Provider=Microsoft.ACE.OLEDB` that I had been using.

You are of course quite correct on the derived types shown in the debugger window being not related to the `UseColumnDataType ` flag. For some reason I thought that was the actual underlying cell `.DataType`  value. Upon closer inspection, that's clearly not the case.

However, when *not* [assigning System.String](https://github.com/gojimmypi/ExcelDataReader/blob/8a043450aa437d89c9b1c41b2248be0bf05fd917/src/ExcelDataReader.DataSet/ExcelDataReaderExtensions.cs#L121) in `AsDataTable` the resultant XML string generated in my code like this:

```
thisDS.WriteXml(myStringWriter, XmlWriteMode.WriteSchema)
``` 

goes from this:

```
<NewDataSet>
  <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:msprop="urn:schemas-microsoft-com:xml-msprop">
    <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="mydataset" msprop:visiblestate="visible">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="ID" type="xs:string" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:complexType>
    </xs:element>
  </xs:schema>
  <mydataset>
    <ID>12345</ID>
  <mydataset>
```
to this:
```
  <NewDataSet>
  <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:msprop="urn:schemas-microsoft-com:xml-msprop">
    <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
      <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="mydataset" msprop:visiblestate="visible">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="ID" msdata:DataType="System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" type="xs:anyType" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:complexType>
    </xs:element>
  </xs:schema>
  <mydataset>
      <ID xsi:type="xs:double" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">12345</ID>
  </mydataset>
```
which, at first glance does not look like much of a difference, but see the `ID` field example: start repeating `xsi:type="xs:double" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"` for every cell in every row, and the difference in memory requirements becomes quickly apparently for large datasets. 

Note that in this case, the ID field _does_ have a type assigned: `xsi:type="xs:double" `  even with `UseColumnDataType ` set to false.  However, I'm not entirely sure  why that's the case. I suspect that since it is already define as `System.String` and not `typeof(object)` the respective row item's `.DataType` property is left alone?

I'm thinking at this point, there's _nothing_ in the code at all for this, but that instead the `WriteXml` does the same thing that the debugger does at runtime: infers data types for objects, but when explicitly set to a `System.String` it does not?

The PR I submitted does solve this XML type problem, but perhaps it should have a different name and/or comments?

**Comment by andersnm** [comment]
Hi @gojimmypi,

Hope you are you working with a (legacy) API that takes XML datasets as input? Otherwise it's kind of extreme to go through `CreateReader()` -> `AsDataSet()` -> `WriteXml()` -> XML parser - just to get the data :-)

Regarding your PR, I'm quite reluctant to change the default type from `object` to `string` in `DataColumn.DataType`. There's been reports of Mono throwing exceptions when individual cell values have different types from the column's type, so this would make that problem worse.

In fact, the whole `UseColumnDataType` thing is kind of legacy and should be reimplemented differently and pr-datatable in a breaking v4 release. It would be nice to get rid of the second pass and finally fix that Mono issue.

I think the verbose XML represents the internal state of the DataSet correctly. Although it's unfortunate the namespace prefix declarations gets repeated. Maybe that could be customized or overridden somehow, but I won't investigate that.

If you really need a custom DataSet serialization format, IMHO your best way forward is to write your own `AsDataSet` or `WriteXml` variant. `AsDataSet` is just a light wrapper over `reader.Read()` and `reader.GetValue()` with plenty of bells and whistles to handle many use cases.

**Comment by gojimmypi** [comment]
Hi @andersnm 

Actually, I am using a (somewhat legacy) call to a SQL Server stored proc with a `@param as xml` to load a `DataTable` into a SQL table. It works quite well with the `WriteXml` converting a `DataSet` to XML strings (for the SQL `xml` parameter). I'm certainly up for suggestions if you are aware of a better means of getting XLS data into SQL.

I went looking for a new solution when I started seeing some odd problems with occasionally missing data in mixed-format columns with the `Provider=Microsoft.ACE.OLEDB` , despite connection settings  (large datasets with mostly numbers, but occasionally non-numeric strings in a field). 

Note that the namespace prefixes don't just get repeated - there's also individual cell types that are assigned. 

I'm not familiar with the problems with Mono. Are you referring to https://github.com/ExcelDataReader/ExcelDataReader/issues/409 ?

I can certainly understand your reluctance to make a change to something already not as desired. 

What do you think if I perhaps modified my PR to instead of forcing string types when `UseColumnDataType` is False, to instead have a new configuration parameter, perhaps a boolean `ForceStringType` in [ExcelDataSetConfiguration](https://github.com/ExcelDataReader/ExcelDataReader/blob/2f14bd4a53186b1c99de05efe4dbee2de1fd3725/src/ExcelDataReader.DataSet/ExcelDataSetConfiguration.cs)?  I would think that a genuinely "no type", (not even "object" default) explicit string dataset would have values to others.

**Comment by andersnm** [comment]
Hi @gojimmypi,

I believe the ideal way to import from Excel to SQL Server is using [SqlBulkCopy](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy) with an `IExcelDataReader` instance - which implements `IDataReader`. 

This stackoverflow seems to indicate it works, with some additional code for the column mappings: https://stackoverflow.com/q/60266053

Although never used it myself, I assume this requires high quality input Excel files where all values have the correct types. If the data is of lower quality, I might [override the IDataReader](https://github.com/ExcelDataReader/ExcelDataReader/issues/268#issuecomment-323567940), or implement a plain reader loop for cleaning up and inserting directly with `ExecuteNonQuery` or some ORM/micro-ORM.  I wouldn't use AsDataSet for anything where performance is important.

Indeed #409 is one of the related Mono reports yes. I doubt anything will change here until somebody does a bigger overhaul for a major version.

**Comment by gojimmypi** [comment]
Hi @andersnm, 

That looks like a great bulk copy solution. I should have known there would be a class library. I didn't know there was anything other than the [bulk copy utility](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15) (that doesn't work very well for my purposes for several reasons). Thanks for pointing out the class-library version.

Indeed I don't trust the XLS for quality, so I initially import everything into an `nvarchar`-based workspace table, and then do conditional type conversions and other business logic in a second step to update the respective the target SQL table.

Thanks for your feedback. Cheers.
