### ISSUE TITLE
is it possible to expose the "stream position"

### ISSUE THREAD

**Issue by Seabizkit** [ExcelDataReader/ExcelDataReader#451]
Is it possible to enhance ExcelDataReader to expose stream positions?

like being able to set the stream positions?... 
I'm guessing NOT as it has to be read as type of file which doesn't expose this, in away which is understandably (does that sentence even make sense)?

So my understanding is, that you can not simply SKIP and TAKE in the file,
as it reads "line by line"..... otherwise it would have to parse the entire file first which is counter to what streaming is.

is it possible to add functionality to set the stream position.
aka...
open file, "read line" several times, get seek position of say 33rd read line, close file.
open same file, and say set position of 33rd "read line".

This would allow for much faster traversing through the file.

**Comment by andersnm** [comment]
Hi @Seabizkit,

Could you please explain a bit more about your use case, how large files? How many files? XLS or XLSX? How long does it take, how much time is spent on seeking? Perhaps attach a big workbook to repro and benchmark ourselves

If your workbooks are big and using AsDataSet, try to set `UseColumnDataType = false` in the configuration (which halves the amount of processing). Also,  if performance is important, you should generally use the reader methods instead of AsDataSet as there is some overhead there.

(technically exposing the stream position wouldn't be useful, as it would only point at the end of some buffer, and can't be reversed back to an actual row. An alternative is some kind of `SeekToRow(rowIndex)` but I suspect that involves more code than its worth)

**Comment by Seabizkit** [comment]
I think you got what i was asking by your last paragraph, i will look into UseColumnDataType.

Large file say 500 k rows, either xls or xlsx. I am currently using  AsDataSet, and using option to specify whether to include row or not, to act like a sort of skip and take.
(but the issue with this is, it still iterates over all rows, would be nice if there was a nicer way of skipping and taking rows, without having to read the entire file rows or iterating over rows to ignore)

**Comment by appel1** [comment]
Because of how both the binary and xml formats work we have to read it all or we might miss rows and cells. If we could be sure the binary files are up to spec we wouldn't have to but there are so many broken .xls files out there that we have to assume they are broken.

**Comment by Seabizkit** [comment]
thanks
