### ISSUE TITLE
After I packaged the Unity program, I can't get data from IExcelDataReader

### ISSUE THREAD

**Issue by HUSTlwr** [ExcelDataReader/ExcelDataReader#464]
I tried two methods you mentioned:
1：
`IExcelDataReader iExcelDR = ExcelReaderFactory.CreateOpenXmlReader(fs);`
`DataSet ds = iExcelDR.AsDataSet();`

After I packaged the Unity program and ran exe, "NullReferenceException" would happen. And after I checked, I found the value of "ds" is null. 

2：
`IExcelDataReader iExcelDR = ExcelReaderFactory.CreateOpenXmlReader(fs);`
`string test = "";`
`do`
`{`
`    while (iExcelDR.Read())`
`    {`
`          string Str = iExcelDR.GetString(1);`
`          test += Str;`
`    }`
`} while (iExcelDR.NextResult());`

After I packaged the Unity program and ran exe,  I found the value of test didn't change, it's also "".

The type of my file is ".xlsx". And both methods were useful when I ran program in the Unity Editor. I don't know what the problem is.

**Comment by HUSTlwr** [comment]
And there is the dll I used:
Excel.dll
ICSharpCode.SharpZipLib.dll

My using:
using System;
using System.Collections.Generic;
using System.IO;
using System.Windows.Forms;
using System.Data;
using UnityEngine;
using Excel;
using OfficeOpenXml;
using System.Drawing;

**Comment by andersnm** [comment]
Hi,

Could you please try a newer version of ExcelDataReader? It's been more than 5 years and several versions since the assembly dll was called "Excel.dll".

The old version could return null from AsDataSet if f.ex the filestream is invalid, but newer versions should fail earlier in with an error message.

Reference
https://github.com/ExcelDataReader/ExcelDataReader/blob/71500c956d9afb6edc8b2c15322fee27384d194a/Excel/ExcelOpenXmlReader.cs

**Comment by HUSTlwr** [comment]
Thanks!
