### ISSUE TITLE
OOM in ExcelDataReader reading big file

### ISSUE THREAD

**Issue by yuzhangyi** [ExcelDataReader/ExcelDataReader#489]
Hi, everyone,

       When I try to use "ExcelDataReader" to read one 1GB excel file, it meets OOM issue, could you help have a look? The issue is happened at method "AsDataset", thanks!
       Nuget version: ExcelDataReader.3.6.0,   ExcelDataReader.DataSet.3.6.0

            using (var stream = File.Open(fileName, FileMode.Open, FileAccess.Read))
            {
                IExcelDataReader reader;
                var file = new FileInfo(fileName);
                if (file.Extension.Equals(".xls"))
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                else if (file.Extension.Equals(".xlsx"))
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                else
                    throw new Exception("Invalid FileName");

                var result = **reader.AsDataSet(new ExcelDataSetConfiguration()
                {
                    ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
                    {
                        UseHeaderRow = true
                    }
                });**

                var dataTable = result.Tables[sheetName];
                var row = dataTable.Rows[0];
            }

**Comment by andersnm** [comment]
Hi @yuzhangyi, 

As a general rule, if you plan to work with large files, you should not use AsDataSet() since this loads everything into memory. The error message indicates you don't have enough RAM on your system to load everything into memory. AsDataSet can use additional memory beyond the physical file size: F.eks if you create an empty DataSet with millions of rows and no data, it still takes hundreds of megabytes without touching this library.

Instead you should use reader.Read(), reader.GetValue(), reader.NextResult() etc and process the data per row.

If you really, really want to use AsDataSet, and insist there is enough RAM, a bit more info could be useful:

- Are you running your program as a 32-bit program?
- How much RAM do you have on your system?
- How much RAM does your OS report the process to use when it produces the OOM?
- Which .NET runtime are you using? (.NET Framework, .NET Core, Blazor Webassembly or Server, Xamarin, Mono etc?)
- Which OS? Is it a 64bit system?
- Can you provide the stack trace? (so we can see if it crashes while the datatable is filled, or before)
- Can you upload the file somewhere so we can reproduce? (this is the most important, and without it we may not be able to resolve any problems)

**Comment by yuzhangyi** [comment]
@andersnm , thanks for your information and help. In order to avoid consume too much memory, I also have a try with reader.Read(), but it seems it is hard to get one row, one cell or use range? Could you help give some guidance? The following is requirement on my side:
1. Support range in reading excel file, for example "A1:E5"
2. It can get each row's data and ordinal.
3. It can get each cell's value, ordinal and type.

**Comment by andersnm** [comment]
@yuzhangyi The reader API is not particularly hard if you are familiar with it. Use `GetValue()` to get a cell value, and `GetFieldType()` to get its type. If you write an indexed loop over the columns, you have the ordinal. An untested starting point could be something like this.

```c#
while (reader.Read()) {
    Console.WriteLine("Reading row...");
    for (var i = 0; i < reader.FieldCount; i++) {
        Console.WriteLine("Got value {0} of type {1} at column index {2}", reader.GetValue(i), reader.GetFieldType(i), i);
    }
    Console.WriteLine("Done reading row...");
}
```
