### ISSUE TITLE
Could someone fix the Project so that it works

### ISSUE THREAD

**Issue by Seabizkit** [ExcelDataReader/ExcelDataReader#49]
Hi have had to change several things to get this to work.

I am talking about the TestApp
1. One of the references is confused. had to remove Excel.4.5 and add back. (strange behavior)
   Was complaining about missing bin/Debug45/Excel.dll

2.The reference flies are missing from TestApp to PCLStorage and PCLStorage.Abstractations
if you don't add this is will complain about method not implemented i the Portable Project.
1. After all that when i try and Test a file it says that it has no
   _workbook..... line " for (int ind = 0; ind < _workbook.Sheets.Count; ind++)"

_workbook is null.... I think this has to do with all the async methods.

Could be wrong about all this but would be nice if it just worked out the box.

**Comment by Seabizkit** [comment]
just to add to this.... its way more complicated to use Excel.4.5 vs Excel

I think a better tutorial is needed for what is all needed to make Excel.4.5 work... as it seems to require a lot more other refereanses

**Comment by Seabizkit** [comment]
Hi, Further to this.... I assume that moving to 4.5 the goal was to remove a reference to ICSharpCode.SharpZipLib.

Could someone give me an explanation of why. (it would be most useful for my own learning)
and now 4 references are needed;
ExcelDataReader.Desktop
ExcelDataReader.Portable
PCLStorage
PCLStorage.Abstractions

**Comment by Ian1971** [comment]
The stable version is in the master branch. That reflects the version in nuget. You are welcome to use that.

The version in the develop branch is largely untested. I switched the default branch to develop just so I could get some feedback as otherwise it would be only me testing it and I can't release it like that. So, thank you for your comments, I will look into them.

The Excel 4.5 version has exactly the same interface as the 2.0 version so I'm not sure why you think it much harder to use. 

The main change in the version in the develop branch is that the 4.5 version uses a Portable Class Library. Meaning, in theory, it is easier to get it to work on different platforms that support PCL, SharpZipLib has gone because there is a framework zip implementation that is used instead.
The new references to PCLStorage are to support the PCL version, however, it was more a convenience at the time to use those than roll my own storage abstraction. It should be possible to inline those abstractions but I'd lose benefit of uses a third-party library (i.e. I don't have to maintain that bit). Does having extra references cause you a problem? If so, I'd like to understand that  better, for my own benefit.

I'll look into the compilation issues you mentioned,.

Thanks

**Comment by Seabizkit** [comment]
Hi Ian1971
Thanks....
Now that i can been looking/staring at it for some time.
I downloaded the lib from Github. (I will try the nuget later.)

Just to clarify. To me it was/is confusing as to why all of these are needed.;
ExcelDataReader.Desktop
ExcelDataReader.Portable
PCLStorage
PCLStorage.Abstractions

You imply(above) that it can be used without.....PCLStorage.
Its not clear how to remove this abstraction if you are referencing the lib without modifying it.
(lets come back to this one later)

What does not work, The TestApp with an xlsx(2007) file... seems to work with a xls(2003) file.

Saying that if I build a simple console App and Reference these
Excel.dll
ExcelDataReader.Desktop.dll
ExcelDataReader.Portable.dll
PCLStorage.dll
PCLStorage.Abstractions.dll

I am able to read both xls and xlsx.

What I was suggesting is that when some downloads the project that it include these references in the TestApp;

ExcelDataReader.Desktop.dll
ExcelDataReader.Portable.dll
PCLStorage.dll
PCLStorage.Abstractions.dll

As it does not work with out them... or well i can not understands what i would need to do.

**Comment by ExcelDataReader** [comment]
It's possible I messed up the references in TestApp, because I was recently
running it against the stable nuget package to compare it to the develop
branch.


On Sun, Jan 11, 2015 at 3:37 PM, Seabizkit <notifications@github.com> wrote:

> Hi Ian1971
> Thanks....
> Now that i can been looking/staring at it for some time.
> I downloaded the lib from Github. (I will try the nuget later.)
>
> Just to clarify. To me it was/is confusing as to why all of these are
> needed.;
> ExcelDataReader.Desktop
> ExcelDataReader.Portable
> PCLStorage
> PCLStorage.Abstractions
>
> You imply(above) that it can be used without.....PCLStorage.
> Its not clear how to remove this abstraction if you are referencing the
> lib without modifying it.
> (lets come back to this one later)
>
> What does not work, The TestApp with an xlsx(2007) file... seems to work
> with a xls(2003) file.
>
> Saying that if I build a simple console App and Reference these
> Excel.dll
> ExcelDataReader.Desktop.dll
> ExcelDataReader.Portable.dll
> PCLStorage.dll
> PCLStorage.Abstractions.dll
>
> I am able to read both xls and xlsx.
>
> What I was suggesting is that when some downloads the project that it
> include these references in the TestApp;
>
> ExcelDataReader.Desktop.dll
> ExcelDataReader.Portable.dll
> PCLStorage.dll
> PCLStorage.Abstractions.dll
>
> As it does not work with out them... or well i can not understands what i
> would need to do.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/49#issuecomment-69498426>
> .
>



-- 

Ian Cox
C.T.O.

Release  Mobile

m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.releasemobile.com

Registered in England.  Number 06323661

**Comment by andersnm** [comment]
Hope its ok to close this now. The develop branch should work out of the box in latest VS2017
