### ISSUE TITLE
CreateReader from Stream Fails

### ISSUE THREAD

**Issue by toddplayer** [ExcelDataReader/ExcelDataReader#571]
Hello. I am trying to read an xlsx file from an Azure File Share using the AzureShareFileClient and I am not able to get the code below to execute. It was working before on an older Azure Storage library but switching to the newer Azure.Storage.Files.Shares seems to have broken it. The thing is I get no error or other output - this is a .Net console app and it just stops running when it reaches ExcelReaderFactory.CreateReader in the snippet below. I have checked all the obvious things I can think, including if the file exists using if (await fileToLoad.ExistsAsync()) and that returns true so I can see the file in question. Do you have any suggestions of how I might be able to get this to work? 
 
using (var stream = await fileToLoad.OpenReadAsync())
                {
                   Console.WriteLine("success 1");
                    using (var reader = ExcelReaderFactory.CreateReader(stream))
                    {
                        Console.WriteLine("success 2");
                        ...do more stuff
                    }
                }

**Comment by andersnm** [comment]
As you suggest, sounds like `Azure.Storage.Files.Shares` is broken since it worked before. 

Does "it just stops running" mean it terminates without an exception or error message, or that it hangs forever? I don't have Azure, alas I can't do much else than suggest random stuff:

- make sure that it's not taking very long time for some reason
- try the non-async `OpenRead()` version: maybe the stream is in a kind of "async mode" if you open it with `OpenReadAsync` - specially since ExcelDataReader does not use async
- try to do some tests without ExcelDataReader, f.ex open a text file and dump it using the streams sync `Read()` method

**Comment by toddplayer** [comment]
Thanks for the reply. To answer your question, yes it just stopped running with no exception or error message.

I was able to do some further testing with it today along the lines of your suggestions around the non-async method and that seems to have been part of the problem. Compounding that was a problem with a particular Excel file I was doing all my testing with. Saving that and uploading to Azure again in combination with using the non-async Azure methods got it working for me.
