### ISSUE TITLE
 ExcelReaderFactory.CreateReader() requires all data stream to create a reader

### ISSUE THREAD

**Issue by Peter43784** [ExcelDataReader/ExcelDataReader#585]
I have noticed that CreateReader method from ExcelReaderFactory is dependent on the size of a stream. 

In my case I try to read only couple of rows(10) from large .xslx file. I would expect it to take same amount of time for each file.
It turned out that depending on the file size time required to read 10 rows is different(less than a second for a file with 20 rows and more than 3 seconds for 20k file).  

After adding watchers I see that most of the time is consumed by ExcelReaderFactory.CreateReader(stream, new ExcelReaderConfiguration()

The main reason is the constructor of  ExcelOpenXmlReader  which calls Reset(); Does it have to call that?

Code sample I use in my application:
 var reader = ExcelReaderFactory.CreateReader(stream, new ExcelReaderConfiguration());
            var count = 10;
            while (reader.Read())
            {
                if (int > count)
                {
                    yield break;
                }
                else
                {
                    var row = GetRow(reader);
                    yield return row;
                    i++;
                }
            }

**Comment by andersnm** [comment]
Hi, your observation is correct and by design: ExcelDataReader needs to read through the spreadsheet contents once to correctly determine the "RowCount" and "FieldCount" properties. Without this behavior the library would randomly return wrong data depending on the file. It was discovered and implemented after this report: https://github.com/ExcelDataReader/ExcelDataReader/issues/271#issuecomment-326989381

**Comment by Peter43784** [comment]
@andersnm is there a way to overcome this. For ex If I want to just read sheet names I don't really wanna read whole file
