### ISSUE TITLE
cell values are not updated when using a formula. Required to open  and safe Excel file

### ISSUE THREAD

**Issue by hilgev** [ExcelDataReader/ExcelDataReader#60]
Hi,

First of all, I need to say that the ExcelDataReader is a very nice feature. I am already using it for a while now and it a pretty good way to read excel files without having MS-Office installed.

Unfortunately, I encountered an issue with reading data in Excel files (using excelReader.AsDataSet()).

Cell valuas that rely on a formula are not updated. 

I.e. when I use a formula to manipulate a date. Lets say: =TODAY()-10 and I read it on the day that I opened and save the Excel file it is retrieved properly. 

But when I read it the next day (or any day in the future) without touching the Excel-file, I recieve the outcome of the formula as when it was last saved.

Is this familiar behaviour and is there a solution? It makes no sence to reopen and save the excel file each time prior to reading the data using the ExcelDataReader.

Dying for an answer here... 

Kind regards

**Comment by Ian1971** [comment]
Ah, there is no way around that really, because the results of the formula
are stored in the excel file at the point it was last saved.
ExcelDataReader displays that result.
To dynamically calculate formulas would be a big undertaking.

On Thu, Mar 26, 2015 at 10:22 AM, hilgev <notifications@github.com> wrote:

> Hi,
>
> First of all, I need to say that the ExcelDataReader is a very nice
> feature. I am already using it for a while now and it a pretty good way to
> read excel files without having MS-Office installed.
>
> Unfortunately, I encountered an issue with reading data in Excel files
> (using excelReader.AsDataSet()).
>
> Cell valuas that rely on a formula are not updated.
>
> I.e. when I use a formula to manipulate a date. Lets say: =TODAY()-10 and
> I read it on the day that I opened and save the Excel file it is retrieved
> properly.
>
> But when I read it the next day (or any day in the future) without
> touching the Excel-file, I recieve the outcome of the formula as when it
> was last saved.
>
> Is this familiar behaviour and is there a solution? It makes no sence to
> reopen and save the excel file each time prior to reading the data using
> the ExcelDataReader.
>
> Dying for an answer here...
>
> Kind regards
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ExcelDataReader/ExcelDataReader/issues/60>.
>



-- 

Ian Cox
C.T.O.

System Sync
m:            Matrix Studios, 91 Peterborough Road, London, SW6 3BU
w:            http://www.systemsyncsolutions.com
<http://www.releasemobile.com/>

Registered in England as systemsync solutions ltd.
Number: 9326325 VAT: 202729923

**Comment by hilgev** [comment]
Hello,

Thank you for the fast reply. I was already afraid that there was no solution for this problem.

Kind regards.
