### ISSUE TITLE
exceldatareader.Read() continues past end of document

### ISSUE THREAD

**Issue by captainjono** [ExcelDataReader/ExcelDataReader#76]
Hello,

Im not entirely familiar with all the functions of excel, but im finding the data reader is not stopping once it gets to a row of cells that hasnt got any data. This is what i would expect using a data reader in any other environment, but i understand if i am using MSExcel that i can scroll down continuously and it never "gets to the end of the document". Im assuming this is what the data reader is doing too.

I couldnt find any info to back this up, so i am posing the question. How do i know i have come to the end of the document? Do i just wait for a row that has null values in every column i am interrogating and assume so? Basically writing a parser for an xls as a feed import process into our system. Each row represents a new record i need to merge. There are only about 20 rows in the spreadsheet im using for testing, but the reader keeps on trucking on past them!

<code>
 while(_reader.Read() & _reader.IsValid)
{
//do something with row
}
</code>

**Comment by Ian1971** [comment]
Exceldatareader will read all rows that the spreadsheet says it has.
Otherwise it doesn't know that there might be 30 blank rows then some
data.  If excel keeps on scrolling past the end of your data that indicates
that  the spreadsheet has a lot of blank rows at the end.

If you can't change your spreadsheet then you'll need to write something to
check if all the columns that should have data are blank and assume that is
the end. Perhaps if there is one column that always has data then you can
just check that one column.

**Comment by captainjono** [comment]
Thanks for the quick reply. This makes sense to me.
