### ISSUE TITLE
Portable class library

### ISSUE THREAD

**Issue by Ian1971** [ExcelDataReader/ExcelDataReader#9]
Convert the library to a portable class library so maitenance and integration with different frameworks is easier.

**Comment by anders9ustafsson** [comment]
@Ian1971 Really great to see your effort of providing *ExcelDataReader* as a portable library also. 

I just noticed that the portable project is currently targeting PCL profile 7, i.e. .NET Framework 4.5 and Windows 8. 

I checked, and the project will also builds successfully if you re-target it to profile 111, i.e. .NET 4.5, Windows 8 **and** Windows Phone 8.1 (non-Silverlight). 

So, unless there are any caveats that I am overlooking, I recommend that you re-target to profile 111 to further extend the applicability of *ExcelDataReader*.

**Comment by Ian1971** [comment]
Thanks for the info, I'll look into it.

**Comment by andersnm** [comment]
Now that the library targets netstandard1.3, I'm inclined to close this.

There might be future discussions whether to support a lower version of netstandard, and thus more platforms.

ExcelDataReader currently targets netstandard1.3 because of this commit 408829020dc2f458ad29ec1c4a56158d3c7a3e22 and it looks we could go back to netstandard1.2 with little effort.

Iirc we could drop to netstandard1.1 if it weren't for the zip-stuff (System.IO.Compression).

For reference, this table shows what's supported by each netstandard version:
https://github.com/davidfowl/NetStandard/blob/master/README.md#mapping-net-standard-versions-to-platforms
