### ISSUE TITLE
Support ConvertOaDate parameter in ExcelOpenXmlReader

### ISSUE THREAD

**Issue by andrant** [ExcelDataReader/ExcelDataReader#90]
I have two files with date and time formated cells, both files have the same values.
If  file is binary (XLS) exceldatareader takes values as double, case openxml (XLSX) reader takes values as datetime. 
As a result I have for example, 42148 (case XLS), or 5/24/2015  12:00:00 AM (case XLSX) output.
Similar issue reading time formated cells, different output.

Is it possible to get the correct output (datetime) from different type excel files?

**Comment by pwitvoet** [comment]
Setting `ConvertOaDate` to true should give the behavior that you're looking for.

Note that `AsDataSet()` and `AsDataSet(bool convertOADateTime)` overwrite `ConvertOaDate` (`AsDataSet()` just calls `AsDataSet(false)` internally), so even when you set `ConvertOaDate` to true, calling `AsDataSet()` instead of `AsDataSet(true)` will revert it to false.

**Comment by andersnm** [comment]
The bug is you didn't get doubles from both =) @pwitvoet is likely correct, setting `ConvertOaDate` to true should do it. Suggest to keep open until either ConvertOaDate is no longer needed or the behavior is consistent across the formats.
